var myGameTxt = {
    name: "Act 1",
    actNumber: 1,
	scenes: [
        {
            name: "Scene1",
            sceneNumber: 1,
            texts: [
                ["This wasn’t my house. I wandered in the streets for some times. Here I stood, at the gate. There was a ", "regular", false],
                ["road", "regular", true],
                [" that lead to a ", "regular", false],
                ["door.", "regular", true],
                [" I may have been too far away from home now. ", "regular", false],
                ["I hated to see that house again.", "angry", false]
            ],
            items: [
                {
                    name: "road",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: "The road was short. It was mainly made of dirt. It had not been maintained in a while.",
                    useWin: true,
                    useTxtOpen: "I might as well.",
                    goWin: true,
                    goTxtOpen: "I might as well.",
                    hitWin: false,
                    hitTxt: "Why would I hit dirt?",
                    inspectWin: false,
                    inspectTxt: "It was dirt, what do you want me to say?",
                    waitWin: false,
                    waitTxt: "I waited for a bit. A bird flew by. Time to move",
                    acceptWin: true,
                    acceptTxt: "This was the last time I had to go in that house. I could feel it."
                },
                {
                    name: "door",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: "The door looked closed from up here. I could try to open it. Needed to go to it though.",
                    useWin: false,
                    useTxtOpen: "I needed to get closer to it.",
                    goWin: true,
                    goTxtOpen: "I might as well.",
                    hitWin: false,
                    hitTxt: "I mean, I could. Needed to get closer though.",
                    inspectWin: false,
                    inspectTxt: "I was too far away to see anything.",
                    waitWin: false,
                    waitTxt: "I waited for a bit. The door kept shut. Time to move.",
                    acceptWin: false,
                    acceptTxt: "What do you mean?"
                },
                {
                    name: "leave",
                    leftWin: true,
                    leftTrue: "I decided to go. There was nothing for me there.",
                    leftFalse: "I felt drawn to the house. I couldn't leave just yet."
                }
            ],
        },
		{
            name: "Scene2",
            sceneNumber: 2,
			texts: [
                ["There I was. The ", "regular", false],
				["door", "regular", true],
				[" was right there. ", "regular", false],
                ["The air outside was cold and wet. I'd rather go inside again... ", "sad", false],
                ["There also was a ", "regular", false],
				["window", "regular", true],
                [", next to it, on the left. Everything looked frozen in time. I didn’t know what to think about it. There was a ", "regular", false],
				["doorbell.", "regular", true],
				[" I could just… ring it. ", "regular", false],
			],
			items: [
                {
                    name: "window",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: 0,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The curtains were drawn. Hard to say if anyone was here.",
                    lookTxtOpen: "The window was now broken. Wouldn't try and touch it.",
                    useWin: false,
                    useTxt: "It’s closed shut. Can’t open it from this side.",
                    useTxtOpen: "I cut my finger on the glass. Stung a bit.",
                    goWin: false,
                    goTxt: "Yeaaah. No. It was closed, and I could not see the other side.",
                    goTxtOpen: "Sure, it was open... and broken glass. No way I was going through there.",
                    hitWin: false,
                    hitTxt: "The glash shattered. It was sharp. I wouldn't want to go in from here.",
                    inspectWin: false,
                    inspectTxt: "The curtains reminded me of my parents'. Weird.",
                    waitWin: false,
                    waitTxt: "I stood in the reflection. Pale as a ghost. I looked tired.",
                    acceptWin: true,
                    acceptTxt: "I pushed the window, and it opened? Might as well go through it."
				},
                {
                    name: "door",
                    lookOpens: -1,
                    useOpens: 1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "A bit too frail if you ask me. I didn't know if it was unlocked or not.",
                    lookTxtOpen: "It was unlocked after all.",
                    useWin: false,
                    useTxt: "Huh. It was unlocked. Who the Hell would leave it like that?",
                    useTxtOpen: "It was open now. What was there left to do?",
                    goWin: true,
                    goTxt: "I didn't even know if it was opened.",
                    goTxtOpen: "Here goes nothing.",
                    hitWin: true,
                    hitTxt: "I smashed the door. Fuck that door. I was happy it glad it broke.",
                    inspectWin: false,
                    inspectTxt: "The handle was heavy, probably lead. The door must've been decades old.",
                    waitWin: false,
                    waitTxt: "As if the door would magically disappear. Time to move.",
                    acceptWin: true,
                    acceptTxt: "I had to accept going into that house again. One last time."
				},
                {
                    name: "doorbell",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "It looked broken. I’d been surprised if it rang.",
                    useWin: false,
                    useTxt: "Not a sound. Didn’t know what I was expecting.",
                    goWin: false,
                    goTxt: "The doorbell is right there.",
                    hitWin: false,
                    hitTxt: "The bell rang after being hit. Not a sound came from inside.",
                    inspectWin: false,
                    inspectTxt: "The name on it was scratched off. The first letter was the same as mine.",
                    waitWin: false,
                    waitTxt: "Didn't konw what I was waiting for. It was broken.",
                    acceptWin: false,
                    acceptTxt: "The name, though scratched, was my father's. He was gone, wasn't he?"
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I backed off. The air around me was cold.",
                }
			],
		},
		{
            name: "Scene3",
            sceneNumber: 3,
			texts: [
                ["Here I was inside the house.", "regular", false],
                [".. ", "regular", false],
                ["Again. ", "angry", false],
                ["It was dark, and clearly abandonned. ", "regular", false],
                ["I felt alone. ", "sad", false],
                ["The house was just one room with a ", "regular", false],
                ["staircase", "regular", true],
                [" on my right. In the middle of the room, a ", "regular", false],
                ["desk.", "regular", true],
                [" On it, there was a ", "bargain", false],
                ["postcard.", "bargain", true],
                [" There was an old ", "regular", false],
                ["bookshelf", "regular", true],
                [" at the back. Nothing else stood out in this room.", "regular", false],
			],
			items: [
                {
                    name: "staircase",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: 0,
                    acceptOpens: 0,
                    isOpened: false,
                    lookTxt: "It lead somewhere upstairs. There was a door at the top.",
                    lookTxtOpen: "It was open now. Might as well go through.",
                    useWin: false,
                    useTxt: "The door upstairs was locked. Not my lucky day.",
                    useTxtOpen: "The door was opened now. I could just go.",
                    goWin: true,
                    goTxt: "I had to get it open. Otherwise I was stuck down here.",
                    goTxtOpen: "The door was now open! The door creaked when it opened. I entered the next floor.",
                    hitWin: false,
                    hitTxt: "My hand hurt after hitting the door upstairs. It didn't even budge",
                    inspectWin: false,
                    inspectTxt: "The keyhole to the door upstairs was ancient, and rusty.",
                    waitWin: false,
                    waitTxt: "After a while, suddenly, a clic. And the door creaked open.",
                    acceptWin: false,
                    acceptTxt: "This door was the one to my childhood's bedroom. Suddenly the door came open."
				},
                {
                    name: "desk",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: 1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: 1,
                    btnOpens: 3,
                    gotKey: false,
                    canPressBtn: false,
                    isOpened: false,
                    lookTxt: "It was a big oak desk. Dusty though. Looked sturdy enough.",
                    lookTxtOpen: "It was a big oak desk. Dusty though. Looked sturdy enough.",
                    useWin: false,
                    useTxt: "There was a drawer, that was closed shut.",
                    useTxtOpen: "The drawer could now open. Inside, there was a key. I took it.",
                    useTxtBtn: "I entered the code 120896. I heard a click by the bookshelf.",
                    goWin: false,
                    goTxt: "I'm at the desk, though nothing is of note.",
                    goTxtOpen: "I'm at the desk, though nothing is of note.",
                    hitWin: false,
                    hitTxt: "I banged the drawer. With a sharp sound, it actually opened.",
                    inspectWin: false,
                    inspectTxt: "Under the desk was hidden a pad with numbers. What was the combination?",
                    waitWin: false,
                    waitTxt: "Nothing happened. Why am I wasting my time?",
                    acceptWin: false,
                    acceptTxt: "This desk was mine. I had it at my parent's house. The drawer just needed to be hit."
				},
                {
                    name: "postcard",
                    lookOpens: -1,
                    useOpens: 2,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    useCanPressBtn: 1,
                    isOpened: false,
                    lookTxt: `It was a postcard from some touristic island. Said "A piece of Paradise" on the front.`,
                    lookTxtOpen: `It read: "August 12, 1996". The day of my birth.`,
                    useWin: false,
                    useTxt: "I flipped the card to see what was on the back.",
                    useTxtOpen: "What could I do more than flip it?",
                    goWin: false,
                    goTxt: "I wish I could go to wherever the postcard depicts.",
                    goTxtOpen: "I wish I could go to wherever the postcard depicts.",
                    hitWin: false,
                    hitTxt: "I crumbled the postcard. Not sure why...",
                    inspectWin: false,
                    inspectTxt: "There was a signature on the front. I couldn't remember whose it was.",
                    waitWin: false,
                    waitTxt: "Nothing happened.",
                    acceptWin: false,
                    acceptTxt: "It was my dad's. The signature. Why was it his?"
				},
                {
                    name: "bookshelf",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    isDoorOpen: false,
                    lookTxt: "The bookshelf was mostly old and dusty. The books did not look interesting.",
                    lookTxtOpen: "The shelf had moved to its left. Now there was a door behind.",
                    useWin: false,
                    useTxt: "I opened a book at random. It was some encyclopedia. Nothing of notice.",
                    useTxtOpen: "Of course the door was locked. There was a ticking sound, though.",
                    goWin: false,
                    goTxt: "Go where? The bookshelf wouldn't just run away.",
                    goTxtOpen: "Wow. It actually moved. I was impressed.",
                    hitWin: false,
                    hitTxt: "With a swift hit, some of the books fell.",
                    inspectWin: false,
                    inspectTxt: `A book caught my eyes. "The Dark Pool". It felt familiar, but I couldn't tell why.`,
                    waitWin: false,
                    waitTxt: "The ticking sounds faded, then a loud crack. Sounded like the door behind opened.",
                    acceptWin: true,
                    acceptTxt: "This bookshelf belonged to my parents. Long ago. The shelf sled and the door behind was open."
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I left the house. The air outside bit me with cold.",
                }
			],
		},
	],
	complete: false,
    currentScene:0,
    currentAct:0
};