var myGameTxt = {
    name: "Act 1",
    actNumber: 1,
	scenes: [
        {
            name: "Scene1",
            sceneNumber: 1,
            texts: [
                ["This wasn’t my house. I wandered in the streets for some times. Here I stood, at the gate. There was a ", "regular", false],
                ["road", "regular", true],
                [" that lead to a ", "regular", false],
                ["door.", "regular", true],
                [" I may have been too far away from home now. ", "regular", false],
                ["I hated to see that house again.", "angry", false]
            ],
            items: [
                {
                    name: "road",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: "The road was short. It was mainly made of dirt. It had not been maintained in a while.",
                    useWin: true,
                    useTxtOpen: "I might as well.",
                    goWin: true,
                    goTxtOpen: "I might as well.",
                    hitWin: false,
                    hitTxt: "Why would I hit dirt?",
                    inspectWin: false,
                    inspectTxt: "It was dirt, what do you want me to say?",
                    waitWin: false,
                    waitTxt: "I waited for a bit. A bird flew by. Time to move",
                    acceptWin: true,
                    acceptTxt: "This was the last time I had to go in that house. I could feel it."
                },
                {
                    name: "door",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: "The door looked closed from up here. I could try to open it. Needed to go to it though.",
                    useWin: false,
                    useTxtOpen: "I needed to get closer to it.",
                    goWin: true,
                    goTxtOpen: "I might as well.",
                    hitWin: false,
                    hitTxt: "I mean, I could. Needed to get closer though.",
                    inspectWin: false,
                    inspectTxt: "I was too far away to see anything.",
                    waitWin: false,
                    waitTxt: "I waited for a bit. The door kept shut. Time to move.",
                    acceptWin: false,
                    acceptTxt: "What do you mean?"
                },
                {
                    name: "leave",
                    canLeave: false,
                    leftTrue: "I decided to go. There was nothing for me there.",
                    leftFalse: "I felt drawn to the house. I couldn't leave just yet."
                }
            ],
        },
		{
            name: "Scene2",
            sceneNumber: 2,
			texts: [
                ["There I was. The ", "regular", false],
				["door", "regular", true],
				[" was right there. ", "regular", false],
                ["The air outside was cold and wet. I'd rather go inside again... ", "sad", false],
                ["There also was a ", "regular", false],
				["window", "regular", true],
                [", next to it, on the left. Everything looked frozen in time. I didn’t know what to think about it. There was a ", "regular", false],
				["doorbell.", "regular", true],
				[" I could just... ring it. ", "regular", false],
			],
			items: [
                {
                    name: "window",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: 0,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The curtains were drawn. Hard to say if anyone was here.",
                    lookTxtOpen: "The window was now broken. Wouldn't try and touch it.",
                    useWin: false,
                    useTxt: "It was closed shut. Couldn't open it from this side.",
                    useTxtOpen: "I cut my finger on the glass. Stung a bit.",
                    goWin: false,
                    goTxt: "Yeaaah. No. It was closed, and I could not see the other side.",
                    goTxtOpen: "Sure, it was open... and broken glass. No way I was going through there.",
                    hitWin: false,
                    hitTxt: "The glash shattered. It was sharp. I wouldn't want to go in from here.",
                    inspectWin: false,
                    inspectTxt: "The curtains reminded me of my parents'. Weird.",
                    waitWin: false,
                    waitTxt: "I stood in the reflection. Pale as a ghost. I looked tired.",
                    acceptWin: true,
                    acceptTxt: "I pushed the window, and it opened? Might as well go through it."
				},
                {
                    name: "door",
                    lookOpens: -1,
                    useOpens: 1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "A bit too frail if you ask me. I didn't know if it was unlocked or not.",
                    lookTxtOpen: "It was unlocked after all.",
                    useWin: false,
                    useTxt: "Huh. It was unlocked. Who the Hell would leave it like that?",
                    useTxtOpen: "It was open now. What was there left to do?",
                    goWin: true,
                    goTxt: "I didn't even know if it was opened.",
                    goTxtOpen: "Here goes nothing.",
                    hitWin: true,
                    hitTxt: "I smashed the door. Fuck that door. I was glad it broke.",
                    inspectWin: false,
                    inspectTxt: "The handle was heavy, probably lead. The door must've been decades old.",
                    waitWin: false,
                    waitTxt: "As if the door would magically disappear. Time to move.",
                    acceptWin: true,
                    acceptTxt: "I had to accept going into that house again. One last time."
				},
                {
                    name: "doorbell",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "It looked broken. I’d been surprised if it rang.",
                    useWin: false,
                    useTxt: "Not a sound. Didn’t know what I was expecting.",
                    goWin: false,
                    goTxt: "The doorbell is right there.",
                    hitWin: false,
                    hitTxt: "The bell rang after being hit. Not a sound came from inside.",
                    inspectWin: false,
                    inspectTxt: "The name on it was scratched off. The first letter was the same as mine.",
                    waitWin: false,
                    waitTxt: "Didn't konw what I was waiting for. It was broken.",
                    acceptWin: false,
                    acceptTxt: "The name, though scratched, was my father's. He was gone, wasn't he?"
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I backed off. The air around me was cold.",
                }
			],
		},
		{
            name: "Scene3",
            sceneNumber: 3,
			texts: [
                ["Here I was inside the house.", "regular", false],
                [".. ", "regular", false],
                ["Again. ", "angry", false],
                ["It was dark, and clearly abandonned. ", "regular", false],
                ["I felt alone. ", "sad", false],
                ["The house was just one room with a ", "regular", false],
                ["staircase", "regular", true],
                [" on my right. In the middle of the room, a ", "regular", false],
                ["desk.", "regular", true],
                [" On it, there was a ", "bargain", false],
                ["postcard.", "bargain", true],
                [" There was an old ", "regular", false],
                ["bookshelf", "regular", true],
                [" at the back. Nothing else stood out in this room.", "regular", false],
			],
			items: [
                {
                    name: "staircase",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: 0,
                    acceptOpens: 0,
                    isOpened: false,
                    lookTxt: "It lead somewhere upstairs. There was a door at the top.",
                    lookTxtOpen: "It was open now. Might as well go through.",
                    useWin: false,
                    useTxt: "The door upstairs was locked. Not my lucky day.",
                    useTxtOpen: "The door was opened now. I could just go.",
                    goWin: true,
                    goTxt: "I had to get it open. Otherwise I was stuck down here.",
                    goTxtOpen: "The door was now open! The door creaked when it opened. I entered the next floor.",
                    hitWin: false,
                    hitTxt: "My hand hurt after hitting the door upstairs. It didn't even budge.",
                    inspectWin: false,
                    inspectTxt: "The keyhole to the door upstairs was ancient, and rusty.",
                    waitWin: false,
                    waitTxt: "After a while, suddenly, a clic. And the door creaked open.",
                    acceptWin: false,
                    acceptTxt: "This door was the one to my childhood's bedroom. Suddenly the door came open."
				},
                {
                    name: "desk",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: 1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: 1,
                    btnOpens: 3,
                    gotKey: false,
                    canPressBtn: false,
                    isOpened: false,
                    lookTxt: "It was a big oak desk. Dusty though. Looked sturdy enough.",
                    lookTxtOpen: "It was a big oak desk. Dusty though. Looked sturdy enough.",
                    useWin: false,
                    useTxt: "There was a drawer, that was closed shut.",
                    useTxtOpen: "The drawer could now open. Inside, there was a key. I took it.",
                    useTxtBtn: "I entered the code 120896. I heard a click by the bookshelf.",
                    goWin: false,
                    goTxt: "I'm at the desk, though nothing is of note.",
                    goTxtOpen: "I'm at the desk, though nothing is of note.",
                    hitWin: false,
                    hitTxt: "I banged the drawer. With a sharp sound, it actually opened.",
                    inspectWin: false,
                    inspectTxt: "Under the desk was hidden a pad with numbers. What was the combination?",
                    waitWin: false,
                    waitTxt: "Nothing happened. Why am I wasting my time?",
                    acceptWin: false,
                    acceptTxt: "This desk was mine. I had it at my parent's house. The drawer just needed to be hit."
				},
                {
                    name: "postcard",
                    lookOpens: -1,
                    useOpens: 2,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    useCanPressBtn: 1,
                    isOpened: false,
                    lookTxt: `It was a postcard from some touristic island. Said "A piece of Paradise" on the front.`,
                    lookTxtOpen: `It read: "August 12, 1996". The day of my birth.`,
                    useWin: false,
                    useTxt: "I flipped the card to see what was on the back.",
                    useTxtOpen: "What could I do more than flip it?",
                    goWin: false,
                    goTxt: "I wish I could go to wherever the postcard depicts.",
                    goTxtOpen: "I wish I could go to wherever the postcard depicts.",
                    hitWin: false,
                    hitTxt: "I crumbled the postcard. Not sure why...",
                    inspectWin: false,
                    inspectTxt: "There was a signature on the front. I couldn't remember whose it was.",
                    waitWin: false,
                    waitTxt: "Nothing happened.",
                    acceptWin: false,
                    acceptTxt: "It was my dad's. The signature. Why was it his?"
				},
                {
                    name: "bookshelf",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    isDoorOpen: false,
                    lookTxt: "The bookshelf was mostly old and dusty. The books did not look interesting.",
                    lookTxtOpen: "The shelf had moved to its left. Now there was a door behind.",
                    useWin: false,
                    useTxt: "I opened a book at random. It was some encyclopedia. Nothing of notice.",
                    useTxtOpen: "Of course the door was locked. There was a ticking sound, though.",
                    goWin: false,
                    goTxt: "Go where? The bookshelf wouldn't just run away.",
                    goTxtOpen: "Wow. It actually moved. I was impressed.",
                    goTxtDoorOpen: "I went through the door.",
                    hitWin: false,
                    hitTxt: "With a swift hit, some of the books fell.",
                    inspectWin: false,
                    inspectTxt: `A book caught my eyes. "The Haze". It felt familiar, but I couldn't tell why.`,
                    waitWin: false,
                    waitTxt: "The ticking sounds faded, then a loud crack. Sounded like the door behind opened.",
                    acceptWin: true,
                    acceptTxt: "This bookshelf belonged to my parents. Long ago. The shelf sled and the door behind was open."
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I left the house. The air outside bit me with cold.",
                }
			],
		},
		{
            name: "Scene4",
            sceneNumber: 4,
			texts: [
                ["The room was largely empty, except for a ", "regular", false],
                ["bed.", "regular", true],
                [" Beside it, a ", "regular", false],
                ["bedlamp", "regular", true],
                [" which was lit", "regular", false],
                [", plunging the room in a gloomy atmosphere", "sad", false],
                [". ", "regular", false],
                [" Under the bed was a ", "bargain", false],
                ["teddybear.", "bargain", true],
                [" There was a window, which was broken. ", "regular", false],
                ["On the ground laid some broken ", "angry", false],
                ["glass.", "angry", true],
                [" The moon shone through a hole in the roof.", "accept", false],
                [" There were papers on the ", "regular", false],
                ["wall", "regular", true],
                [" behind me.", "regular", false],
			],
			items: [
                {
                    name: "bed",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: 2,
                    waitOpens: -1,
                    acceptOpens: 2,
                    isOpened: true,
                    lookTxtOpen: "It was... moldy. Must've been here for ages. Pretty gross.",
                    useWin: false,
                    useTxtOpen: "I wouldn't dare touch that. It smelled.",
                    goWin: false,
                    goTxtOpen: "I was at the bed already, not like there was much to see.",
                    hitWin: false,
                    hitTxt: "Kicking the bed proved useless. Some insects crawled from under. I got goosebumps.",
                    inspectWin: false,
                    inspectTxt: "Carved in the bed's framed laid a small copper key. I took it, just in case.",
                    waitWin: false,
                    waitTxt: "The stench made me feel sick. And somewhat nostalgic.",
                    acceptWin: false,
                    acceptTxt: "It was my bed as a child. I knew I hid a key in it. It opened a compartment in the teddybear."
				},
                {
                    name: "bedlamp",
                    lookOpens: -1,
                    useOpens: 1,
                    hitOpens: 1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The lamp casted a dim yellow-ish light on the bed.",
                    lookTxtOpen: "Now it was turned off, and the room went dark. The wall, though, was now glowing.",
                    useWin: false,
                    useTxt: "I pulled on the little chain dangling from the lamp. Now it was off.",
                    useTxtOpen: "I already turned it off. I could still see my way out of here.",
                    goWin: false,
                    goTxt: "The lamp was right there.",
                    goTxtOpen: "The lamp was right there.",
                    hitWin: false,
                    hitTxt: "I smashed the lightbulb. The lamp couldn't shine anymore.",
                    inspectWin: false,
                    inspectTxt: "The end of the chain had a little engraving, with my name on it.",
                    waitWin: false,
                    waitTxt: "Nothing happened.",
                    acceptWin: false,
                    acceptTxt: "I remembered this lamp. It stood in my parent's room when I was little."
				},
                {
                    name: "teddybear",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: `The bear was damp, which made it look gross and malformed.`,
                    lookTxtOpen: `There was a compartment at the back of its head.`,
                    useWin: false,
                    useTxt: "It was heavier than expected. Not sure of its use, though.",
                    useTxtOpen: `Inside there was a note. It said: "Here's to you. Find the final letter".`,
                    goWin: false,
                    goTxt: "The bear's right there.",
                    goTxtOpen: "The bear's right there.",
                    hitWin: false,
                    hitTxt: "I kicked the bear. It made squishy sound.",
                    inspectWin: false,
                    inspectTxt: "The bear had a tag. On it were my initials.",
                    waitWin: false,
                    waitTxt: "I looked like it would crumble right in front of my eyes, but it didn't.",
                    acceptWin: false,
                    acceptTxt: "It was given by my father long ago. Must've been 2 or 3. Loved that bear"
				},
                {
                    name: "glass",
                    useGlassOpens: [4, 1],
                    isOpened: true,
                    lookTxtOpen: "The glass was a bit foggy.",
                    useWin: false,
                    useTxtOpen: "I took a piece of glass and kept it in my coat.",
                    goWin: false,
                    goTxtOpen: "The glass laid at my feet. How many years had this house been in such a state?",
                    hitWin: false,
                    hitTxt: "Stomping on the shards, I created smaller shards.",
                    inspectWin: false,
                    inspectTxt: `Nothing of notice here.`,
                    waitWin: false,
                    waitTxt: "Was the glass supposed to magically fix itself? Surprise, it didn't.",
                    acceptWin: false,
                    acceptTxt: "What was the meaning? That everything would be destroyed in time?"
				},
                {
                    name: "wall",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The walls is littered with newspaper clips from the 1990s.",
                    lookTxtOpen: `Some words were underlined with glowing ink. "We always loved you".`,
                    useWin: false,
                    useTxt: "I tore a newspaper clip, to find the exact same one underneath.",
                    useTxtOpen: "The ink was somehow fresh. Touching it smeared it further.",
                    goWin: false,
                    goTxt: "I was in front of the wall now.",
                    goTxtOpen: "I was in front of the wall now.",
                    hitWin: false,
                    hitTxt: "The wall was study. Wouldn't want to break a bone hitting that...",
                    inspectWin: false,
                    inspectTxt: `One article stood out. It was from this year, about a car accident.`,
                    waitWin: false,
                    waitTxt: "I read the papers in silence. It was pretty ominous.",
                    acceptWin: false,
                    acceptTxt: "The articles were from the time I was born, and grew up. And the day I supposedly died..."
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I came down to the room. I still had chills from before.",
                }
			],
		},
        {
            name: "Scene5",
            sceneNumber: 5,
			texts: [
                ["Behind the bookshelf was a staircase which lead to a tiny square room lit only by a series of five ", "regular", false],
                ["candles.", "regular", true],
                [" In the middle stood an ", "regular", false],
                ["altar", "regular", true],
                [" with a tiny car ", "regular", false],
                ["figurine.", "regular", true],
                [" It was very ominous. ", "sad", false],
                ["Scary, even. It made my blood crawl. ", "anger", false],
                ["That car was a replica of mine. ", "accept", false],
                ["There was a . ", "sad", false],
                ["book", "sad", true],
                [" next to the figurine.", "sad", false],
			],
			items: [
                {
                    name: "candles",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: "The candles were already burning. How is this possible?",
                    useWin: false,
                    useTxtOpen: "I wouldn't dare touch that. I didn't to burn myself.",
                    goWin: false,
                    goTxtOpen: "I was already neat the candles. The room was small enough.",
                    hitWin: false,
                    hitTxtOpen: "One of the candles fell after I kicked the stand. Pretty sure it didn't help.",
                    inspectWin: false,
                    inspectTxtOpen: "The candles' wax was dripping and forming cascading shapes towards the ground.",
                    waitWin: false,
                    waitTxtOpen: "I waited for about an hour. The candles didn't diminish in size. That was... weird.",
                    acceptWin: false,
                    acceptTxtOpen: "These candles were otherworldly. That was the only sound explaination."
				},
                {
                    name: "altar",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    bledOut: false,
                    isOpened: false,
                    lookTxt: "The altar stood proudly in the middle of this tiny chamber. Looked like marble.",
                    lookTxtOpen: "The altar looked scary in the middle of this tiny chamber.",
                    useWin: false,
                    useTxt: "Nothing to do with an altar, I guessed.",
                    useTxtOpen: "I wondered... I took the glass shard and made my hand bleed, let it drip on the altar.",
                    goWin: false,
                    goTxt: "The room was too small for me to move anywhere.",
                    goTxtOpen: "The room was too small for me to move anywhere.",
                    hitWin: false,
                    hitTxt: "Why would I do that?",
                    inspectWin: false,
                    inspectTxt: "It was marble indeed. A black-ish stone with white-grey irregular stripes.",
                    waitWin: false,
                    waitTxt: "Nothing to wait for.",
                    waitTxtBledOut: "I waited for it to have a result. Suddenly, a light, and I was transported elsewhere.",
                    acceptWin: false,
                    acceptTxt: "Where was I? Why were all these items and texts about me? I was again transported elsewhere."
				},
                {
                    name: "figurine",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: true,
                    lookTxtOpen: `This was a family car, similar to the one I bought years ago, when I got my first job.`,
                    useWin: false,
                    useTxtOpen: `I took it in my hands, trembling. Why was I trembling? I put it back.`,
                    goWin: false,
                    goTxtOpen: "The altar was right there. And the car is on it.",
                    hitWin: false,
                    hitTxt: "I threw the car to the ground. Picked it up and placed it back after.",
                    inspectWin: false,
                    inspectTxt: "The car looked hand-painted. There were a few imperfections here and there.",
                    waitWin: false,
                    waitTxt: "I waited, but it didn't do much.",
                    acceptWin: false,
                    acceptTxt: "I bought that exact same car years ago. Last I knew I was driving it. Why am I here then?"
				},
                {
                    name: "book",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    tookTheBook: false,
                    isOpened: true,
                    lookTxtOpen: `It was a copy of "The Haze", a poetry book my mom used to read me when I was little.`,
                    useWin: false,
                    useTxtOpen: "I took the book, maybe to read it later.",
                    goWin: false,
                    goTxtOpen: "I was already at the altar upon which the book sat.",
                    hitWin: false,
                    hitTxt: "Why would I do such a thing? This had sentimental value.",
                    inspectWin: false,
                    inspectTxt: `I read an extract: "You speak of Paradise like it would be forever. I need you here with me"`,
                    waitWin: false,
                    waitTxt: "Waiting didn't do much. At all.",
                    acceptWin: false,
                    acceptTxt: "It was a book about life after death. Weird to have been read that as a kid."
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I rush up the stairs, I did not wait to stay down there for too long.",
                }
			],
		},
        {
            name: "Final scene",
            sceneNumber: 6,
			texts: [
                ["The room was largely empty, except for a ", "regular", false],
                ["bed.", "regular", true],
                [" Beside it, a ", "regular", false],
                ["bedlamp", "regular", true],
                [" which was lit", "regular", false],
                [", plunging the room in a gloomy atmosphere", "sad", false],
                [". ", "regular", false],
                [" Under the bed was a ", "bargain", false],
                ["teddybear.", "bargain", true],
                [" There was a window, which was broken. ", "regular", false],
                ["On the ground laid some broken ", "angry", false],
                ["glass.", "angry", true],
                [" The moon shone through a hole in the roof.", "accept", false],
                [" There were papers on the ", "regular", false],
                ["wall", "regular", true],
                [" behind me.", "regular", false],
			],
			items: [
                {
                    name: "bed",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: 2,
                    waitOpens: -1,
                    acceptOpens: 2,
                    isOpened: true,
                    lookTxtOpen: "It was... moldy. Must've been here for ages. Pretty gross.",
                    useWin: false,
                    useTxtOpen: "I wouldn't dare touch that. It smelled.",
                    goWin: false,
                    goTxtOpen: "I was at the bed already, not like there was much to see.",
                    hitWin: false,
                    hitTxt: "Kicking the bed proved useless. Some insects crawled from under. I got goosebumps.",
                    inspectWin: false,
                    inspectTxt: "Carved in the bed's framed laid a small copper key. I took it, just in case.",
                    waitWin: false,
                    waitTxt: "The stench made me feel sick. And somewhat nostalgic.",
                    acceptWin: false,
                    acceptTxt: "It was my bed as a child. I knew I hid a key in it. It opened a compartment in the teddybear."
				},
                {
                    name: "bedlamp",
                    lookOpens: -1,
                    useOpens: 1,
                    hitOpens: 1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The lamp casted a dim yellow-ish light on the bed.",
                    lookTxtOpen: "Now it was turned off, and the room went dark. The wall, though, was now glowing.",
                    useWin: false,
                    useTxt: "I pulled on the little chain dangling from the lamp. Now it was off.",
                    useTxtOpen: "I already turned it off. I could still see my way out of here.",
                    goWin: false,
                    goTxt: "The lamp was right there.",
                    goTxtOpen: "The lamp was right there.",
                    hitWin: false,
                    hitTxt: "I smashed the lightbulb. The lamp couldn't shine anymore.",
                    inspectWin: false,
                    inspectTxt: "The end of the chain had a little engraving, with my name on it.",
                    waitWin: false,
                    waitTxt: "Nothing happened.",
                    acceptWin: false,
                    acceptTxt: "I remembered this lamp. It stood in my parent's room when I was little."
				},
                {
                    name: "teddybear",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    useTxtOpenOpens: [5, 0],
                    isOpened: false,
                    lookTxt: `The bear was damp, which made it look gross and malformed.`,
                    lookTxtOpen: `There was a compartment at the back of its head.`,
                    useWin: false,
                    useTxt: "It was heavier than expected. Not sure of its use, though.",
                    useTxtOpen: `Inside there was a note. It said: "Here's to you. Find the final letter".`,
                    goWin: false,
                    goTxt: "The bear's right there.",
                    goTxtOpen: "The bear's right there.",
                    hitWin: false,
                    hitTxt: "I kicked the bear. It made squishy sound.",
                    inspectWin: false,
                    inspectTxt: "The bear had a tag. On it were my initials.",
                    waitWin: false,
                    waitTxt: "I looked like it would crumble right in front of my eyes, but it didn't.",
                    acceptWin: false,
                    acceptTxt: "It was given by my father long ago. Must've been 2 or 3. Loved that bear"
				},
                {
                    name: "glass",
                    useGlassOpens: [5, 1],
                    isOpened: true,
                    lookTxtOpen: "The glass was a bit foggy.",
                    useWin: false,
                    useTxtOpen: "I took a piece of glass and kept it in my coat.",
                    goWin: false,
                    goTxtOpen: "The glass laid at my feet. How many years had this house been in such a state?",
                    hitWin: false,
                    hitTxt: "Stomping on the shards, I created smaller shards.",
                    inspectWin: false,
                    inspectTxt: `Nothing of notice here.`,
                    waitWin: false,
                    waitTxt: "Was the glass supposed to magically fix itself? Surprise, it didn't.",
                    acceptWin: false,
                    acceptTxt: "What was the meaning? That everything would be destroyed in time?"
				},
                {
                    name: "wall",
                    lookOpens: -1,
                    useOpens: -1,
                    hitOpens: -1,
                    inspectOpens: -1,
                    waitOpens: -1,
                    acceptOpens: -1,
                    isOpened: false,
                    lookTxt: "The walls is littered with newspaper clips from the 1990s.",
                    lookTxtOpen: `Some words were underlined with glowing ink. "We always loved you".`,
                    useWin: false,
                    useTxt: "I tore a newspaper clip, to find the exact same one underneath.",
                    useTxtOpen: "The ink was somehow fresh. Touching it smeared it further.",
                    goWin: false,
                    goTxt: "I was in front of the wall now.",
                    goTxtOpen: "I was in front of the wall now.",
                    hitWin: false,
                    hitTxt: "The wall was study. Wouldn't want to break a bone hitting that...",
                    inspectWin: false,
                    inspectTxt: `One article stood out. It was from this year, about a car accident.`,
                    waitWin: false,
                    waitTxt: "I read the papers in silence. It was pretty ominous.",
                    acceptWin: false,
                    acceptTxt: "The articles were from the time I was born, and grew up. And the day I supposedly died..."
				},
                {
                    name: "leave",
                    leftWin: false,
                    leftTrue: "I came down to the room. I still had chills from before.",
                }
			],
		},
        {
            name: "Act Title",
            sceneNumber: 7,
			texts: [
                {
                    id: 0,
                    text: [
                        ["Act 1", true],
                        ["The house by the street", false]
                    ]
                },
                {
                    id: 1,
                    text: [
                        ["Act 2", true],
                        ["Up we go", false]
                    ]
                },
                {
                    id: 2,
                    text: [
                        ["Act 3", true],
                        ["More secrets", false]
                    ]
                },
                {
                    id: 3,
                    text: [
                        ["Act 4", true],
                        ["The space beyond", false]
                    ]
                },
                {
                    id: 4,
                    text: [
                        ["Act 5", true],
                        ["Revelations", false]
                    ]
                }
			],
		},
	],
	complete: false,
    currentScene:6,
    currentAct:0
};